#index:
#    path: /
#    controller: App\Controller\DefaultController::index

admin_login_check:
  path: /admin-login-check

admin_logout:
  path: /admin-logout

user_login_check:
  path: /user-login-check

user_logout:
  path: /user-logout